setwd("/Users/carmenbayly/Stat540_Seminars/STAT540_seminar1.2/Gapminder_project")
gDat <- read.delim("gapminderDataFiveYear.txt")
str(gDat)
head(gDat)
tail(gDat)
names(gDat)
ncol(gDat)
length(gDat)
head(rownames(gDat))
dim(gDat)
nrow(gDat)
summary(gDat)
library(lattice)
xyplot(lifeExp ~ year, data = gDat)
xyplot(lifeExp ~ gdpPercap, gDat)
xyplot(lifeExp ~ gdpPercap, gDat, subset = country == "Colombia")
xyplot(lifeExp ~ gdpPercap, gDat, subset = country == "Colombia", type = c("p", "r"))
xyplot(lifeExp ~ gdpPercap | continent, gDat, subset = year == 2007)
xyplot(lifeExp ~ gdpPercap, gDat, group = continent, subset = year == 2007, auto.key = TRUE)
str(gDat)
head(gDat$lifeExp)
summary(gDat$lifeExp)
densityplot(~lifeExp, gDat)
summary(gDat$year)
table(gDat$year)
class(gDat$continent)
summary(gDat$continent)
levels(gDat$continent)
nlevels(gDat$continent)
table(gDat$continent)
barchart(table(gDat$continent))
dotplot(table(gDat$continent), type = "h", col.line = NA)
dotplot(table(gDat$continent), type = c("p", "h"), col.line = NA)
str(gDat$continent)
xyplot(lifeExp ~ gdpPercap, gDat, subset = year == 2007, group = continent, auto.key = TRUE)
xyplot(lifeExp ~ gdpPercap | continent, gDat, subset = year == 2007)
subset(gDat, subset = country == "Uruguay")
gDat[1621:1632, ]
subset(gDat, subset = country == "Mexico", select = c(country, year, lifeExp))
xyplot(lifeExp ~ year, gDat, subset = country == "Colombia", type = c("p", "r"))
(minYear <- min(gDat$year))
myFit <- lm(lifeExp ~ I(year - minYear), gDat, subset = country == "Colombia") 
summary(myFit)
lm(lifeExp ~ year, gDat, subset = country == "Colombia")
