rnorm(n = 10)
?rnorm()
rnorm(10)
set.seed(450)
rnorm(10)
#trying this...
rnorm(10)
set.seed(450)
rnorm(10) #huh. so it works.
#generating lots of Data the R way
n <- 10
B <- 4
x <- matrix(rnorm(n * B), nrow = n)
x <- matrix(rnorm(n * B)) #waht if we omit 'nrow = n'?
str(x)
x <- matrix(rnorm(n * B), nrow = n) #hmm so it is important. what does nrow do?
str(x)
head(x)
x <- matrix(rnorm(n * B)) #hmm so it is important. what does nrow do?
str(x)
head(x, 10)
?nrow
x <- matrix(rnorm(n * B), ncol = n) #hmm so it is important. what does nrow do?
str(x)
head(x, 10) #wierd... must try more things
set.seed(450)
x <- matrix(rnorm(n * B), nrow = n) #hmm so it is important. what does nrow do?
str(x)
head(x, 10)
set.seed(450)
x <- matrix(rnorm(n * B), ncol = n) #hmm so it is important. what does nrow do?
str(x)
head(x, 10)
set.seed(450)
x <- matrix(rnorm(n * B), ncol = 2) #hmm so it is important. what does nrow do?
str(x)
head(x, 10)
head(x,20)
set.seed(450)
x <- matrix(rnorm(n * B), ncol = 5) #hmm so it is important. what does nrow do?
str(x)
head(x, 10)
head(x,20)
set.seed(450)
x <- matrix(rnorm(n * B)) #hmm so it is important. what does nrow do?
str(x)
head(x,40) #so, the vanilla-flavored command just makes a single row
            #of all the numbers generated by 
            #all numbers in n * all numbers in B
            #and you have to define rows or columns if you
            #want a rectangle instead of a line
            #default is 1 column, however many rows.
            #can't make a row or col # that doesn't evenly divide
            #the numbers generated.
#generate lots of data, the awkward ways
##the for loop
x <- matrix(0, nrow = n, ncol = B)
for(j in 1:B) {
  x[ , j] <- rnorm(n)
}
x
#I understand here we created a matrix of zeros, 
#and then for all columns we introduced rnorm.
#playing around...
blarg  <- 5
set.seed(450)
x <- matrix(0, nrow = n, ncol = blarg)
for(p in 2:3) {
  x[p, ] <- rnorm(1)
}
x
sample1 <- rnorm(n)
sample2 <- rnorm(n)
sample3 <- rnorm(n)
sample4 <- rnorm(n)
x <- cbind(sample1, sample2, sample3, sample4)
x <- rnorm(n)
x
for(j in 1:(B - 1)) {
  x <- cbind(x, rnorm(10))
}
x
x <- matrix(rnorm(n * B), nrow = n)
rownames(x) <- sprintf("obs%02d", 1:n)
colnames(x) <- sprintf("samp%02d", 1:B)
x
dim(x)
mean(x[ , 2]) # sample mean for 2nd sample
colMeans(x[ ,2]) #hurray!
apply(x[ , 2:4], mean)

#final response for exercise 1
#matrix construction
B <- 1000
#'''#with rnorm
name  <- rnorm
n <- 10
x10 <- matrix(rnorm(B * n), nrow = B, ncol = n)
n <- 100
x100 <- matrix(rnorm(B * n), nrow = B, ncol = n)
n <- 1000
x1000 <- matrix(rnorm(B * n), nrow = B, ncol = n)
n <- 10000
x10000 <- matrix(rnorm(B * n), nrow = B, ncol = n)
#'''
'''
#with dbeta
name  <- dbeta
n <- 10
x10 <- matrix(dbeta(B * n), nrow = B, ncol = n)
n <- 100
x100 <- matrix(dbeta(B * n), nrow = B, ncol = n)
n <- 1000
x1000 <- matrix(dbeta(B * n), nrow = B, ncol = n)
n <- 10000
x10000 <- matrix(dbeta(B * n), nrow = B, ncol = n)
'''
'''
#with dhyper
name  <- dhyper
n <- 10
x10 <- matrix(dhyper(B * n), nrow = B, ncol = n)
n <- 100
x100 <- matrix(dhyper(B * n), nrow = B, ncol = n)
n <- 1000
x1000 <- matrix(dhyper(B * n), nrow = B, ncol = n)
n <- 10000
x10000 <- matrix(dhyper(B * n), nrow = B, ncol = n)
'''
#sample size
n10 <- ncol(x10)
n100 <- ncol(x100)
n1000 <- ncol(x1000)
n10000 <- ncol(x10000)
#Sample means
xbar10 <- rowMeans(x10)
xbar100 <- rowMeans(x100)
xbar1000 <- rowMeans(x1000)
xbar10000 <- rowMeans(x10000)
#trueSEM
tSEM10 <- sd(x10/sqrt(nrow(x10)))
tSEM100 <- sd(x100/sqrt(nrow(x100)))
tSEM1000 <- sd(x1000/sqrt(nrow(x1000)))
tSEM10000 <- sd(x10000/sqrt(nrow(x10000)))
#obsSEM
oSEM10 <- sd(rowMeans(x10))
oSEM100 <- sd(rowMeans(x100))
oSEM1000 <- sd(rowMeans(x1000))
oSEM10000 <- sd(rowMeans(x10000))
#sampleMeanIQR
IQR10 <- IQR(rowMeans(x10))
IQR100 <- IQR(rowMeans(x100))
IQR1000 <- IQR(rowMeans(x1000))
IQR10000 <- IQR(rowMeans(x10000))
#sampleMeanMad
mad10 <- mad(rowMeans(x10))
mad100 <- mad(rowMeans(x100))
mad1000 <- mad(rowMeans(x1000))
mad10000 <- mad(rowMeans(x10000))
#make table
rownames  <-rbind(n10, n100, n1000, n10000)
trueSEM <- rbind(tSEM10, tSEM100, tSEM1000, tSEM10000)
obsSEM <- rbind(oSEM10, oSEM100, oSEM1000, oSEM10000)
IQR  <- rbind(IQR10, IQR100, IQR1000, IQR10000)
mad <- rbind(mad10, mad100, mad1000, mad10000)
bigtable <- cbind(rownames, trueSEM, obsSEM, IQR, mad)
xname <- c("sampleSize", "trueSEM", "obsSEM", "sampleMeanIQR", "sampleMeanMad")
colnames(bigtable)  <- xname
name
bigtable

#OK:
#Exercise: Generate a reasonably large sample from some normal 
#distribution (it need not be standard normal!). Pick a threshhold. 
#What is the CDF at that threshhold?
#Exercise: Do the same for a different distribution.
#Exercise: Do the same for a variety of sample sizes. 
#Do the two numbers tend to be closer for larger samples?
a  <- rnorm(100)
q <- 1
x <- pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
xobs <- mean(a <= 1) 
print(c(x, xobs))

j  <- rnorm(10000)
q <- 1
k <- pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
kobs <- mean(j <= 1) 
print(c(k, kobs))

b <- rcauchy(100)
r <- -25
y <- pcauchy(r, lower.tail = TRUE, log.p = FALSE)
yobs  <- mean(b <= -25)
print(c(y, yobs))

l <- rcauchy(10000)
r <- -25
m <- pcauchy(r, lower.tail = TRUE, log.p = FALSE)
mobs  <- mean(l <= -25)
print(c(m, mobs))

#norm
print(c(x, xobs))
print(c(k, kobs))
#cauchy
print(c(y, yobs))
print(c(m, mobs))

#Exercise: instead of focuaing on values less than the threshold, 
#focus on values greater than the theshold

a  <- rnorm(100)
q <- 1
x <- pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
upx <- 1-x
upxobs <- mean(a >= 1) 
print(c(upx, upxobs))

#Exercise: Instead of focusing on tail probabilities, focus on the 
#probability of the observed values falling in an interval.

a  <- rnorm(10000)
qa <- 1
qb <- 2
xa <- pnorm(qa, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
xb <- pnorm(qb, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
lessa  <- mean(a < 1)
lessb <- mean(a < 2)
obsInt <- lessb-lessa
#obsInt <- mean(int)  #not right!
#obsInt               #not right!
#xInt  <- xb-xa       #not right!
print(c(xInt, obsInt))

#yey! Done!!

